services:
  api:
    image: hub.intra.mlamp.cn/xiaoming/samepage-py:v1.1
    restart: always
    environment:
      # Server
      SERVER_PORT: 8082
      SERVER_BIND_ADDRESS: 0.0.0.0
      MODE: api


      # Redis
      REDIS_HOST: 10.10.100.150
      REDIS_PORT: 8001
      REDIS_PASSWORD: gpqylk3p6l
      REDIS_DB: 6
      #REDIS_HOST: 127.0.0.1
      #REDIS_PORT: 6379
      #REDIS_PASSWORD:
      #REDIS_DB: 0

      # MySQL
      DB_USERNAME: mz_dev1_test
      DB_PASSWORD: Vs5@EN7jnD
      DB_HOST: m8306.mysql.intra.mlamp.cn
      DB_PORT: 8306
      DB_DATABASE: mz_dev1_test

      # PostgreSQL
      PGVECTOR_DRIVER: psycopg2
      PGVECTOR_HOST: 10.10.6.55
      PGVECTOR_PORT: 6432
      PGVECTOR_DATABASE: pg_vector
      PGVECTOR_USER: pgpool
      PGVECTOR_PASSWORD: psql1234

      # Storage
      # type: local, s3
      STORAGE_TYPE: local
      STORAGE_LOCAL_PATH: storage
      S3_ENDPOINT: https://your-bucket-name.storage.s3.clooudflare.com
      S3_BUCKET_NAME: your-bucket-name
      S3_ACCESS_KEY: your-access-key
      S3_SECRET_KEY: your-secret-key
      S3_REGION: your-region

      # celery
      CELERY_BROKER_URL: redis://:gpqylk3p6l@10.10.100.150:8001/6
      #CELERY_BROKER_URL: redis://127.0.0.1:6379/0
      CELERY_WORKER_AMOUNT: 30

      OPENAI_API_BASE_BLOCK: http://52.90.104.22:30000/v1
      OPENAI_API_BASE_STREAM: http://52.90.104.22:30000/v1
      OPENAI_API_KEY: sk-1hpKQ32AIKGnai3I464444A6316348C99b5dF54d6f1bA774
      OPENAI_ORGANIZATION_ID:
      OPENAI_CHAT_MODEL_GPT_3_5_4K: gpt-3.5-turbo-0613
      OPENAI_CHAT_MODEL_GPT_3_5_16K: gpt-3.5-turbo-16k-0613
      OPENAI_CHAT_MODEL_GPT_4: gpt-4-0613
      SUMMARY_OPENAI_CHAT_MODEL: gpt-3.5-turbo-16k

      # 文本拆分
      EMBEDDING_TEXT_SPLIT_CHUNK_SIZE: 500
      EMBEDDING_TEXT_SPLIT_CHUNK_OVERLAP_SIZE: 20
      EMBEDDING_PDF_TEXT_SPLIT_CHUNK_SIZE: 2048
      EMBEDDING_PDF_TEXT_SPLIT_CHUNK_OVERLAP_SIZE: 50

      SUMMARY_TEXT_SPLIT_CHUNK_SIZE: 14336
      SUMMARY_TEXT_SPLIT_CHUNK_OVERLAP_SIZE: 50

      DETAILED_SUMMARY_TEXT_SPLIT_CHUNK_SIZE: 12288
      DETAILED_SUMMARY_TEXT_SPLIT_CHUNK_OVERLAP_SIZE: 50

      # token限制
      SUMMARY_MAX_TOKEN: 1024
      DETAILED_SUMMARY_MAX_TOKEN: 3072
      SUGGESTED_QUESTIONS_MAX_TOKEN: 1024
      QUESTION_ANSWER_MAX_TOKEN: 2048
      DOCUMENT_CONTENT_TOKEN_LIMIT: 204800
      SUMMARY_DOCUMENT_CONTENT_TOKEN_LIMIT: 102400

      # 问题最大长度
      QUESTION_MAX_LEN: 300

      # 相似度匹配阈值
      MAX_SIMILARITY_SEARCH_SCORE: 0.235
      MAX_SIMILARITY_SEARCH_COUNT: 3

      # 摘要和问题生成温度
      GENERATE_TEMPERATURE: 0.4

      # 联网搜索
      BING_SEARCH_URL: https://api.bing.microsoft.com/v7.0/search
      BING_SUBSCRIPTION_KEY: 85e161ea47d645dea4462793fcc43bf4
      WEB_SEARCH_NUM_RESULTS: 5

    volumes:
      - ./log/app:/app/log
    networks:
      - xming
    deploy:
      mode: replicated
      replicas: 1

  worker:
    image: hub.intra.mlamp.cn/xiaoming/samepage-py:v1.1
    restart: always
    environment:
      # Server
      SERVER_PORT: 8082
      SERVER_BIND_ADDRESS: 0.0.0.0
      MODE: worker


      # Redis
      REDIS_HOST: 10.10.100.150
      REDIS_PORT: 8001
      REDIS_PASSWORD: gpqylk3p6l
      REDIS_DB: 6
      #REDIS_HOST: 127.0.0.1
      #REDIS_PORT: 6379
      #REDIS_PASSWORD:
      #REDIS_DB: 0

      # MySQL
      DB_USERNAME: mz_dev1_test
      DB_PASSWORD: Vs5@EN7jnD
      DB_HOST: m8306.mysql.intra.mlamp.cn
      DB_PORT: 8306
      DB_DATABASE: mz_dev1_test

      # PostgreSQL
      PGVECTOR_DRIVER: psycopg2
      PGVECTOR_HOST: 10.10.6.55
      PGVECTOR_PORT: 6432
      PGVECTOR_DATABASE: pg_vector
      PGVECTOR_USER: pgpool
      PGVECTOR_PASSWORD: psql1234

      # Storage
      # type: local, s3
      STORAGE_TYPE: local
      STORAGE_LOCAL_PATH: storage
      S3_ENDPOINT: https://your-bucket-name.storage.s3.clooudflare.com
      S3_BUCKET_NAME: your-bucket-name
      S3_ACCESS_KEY: your-access-key
      S3_SECRET_KEY: your-secret-key
      S3_REGION: your-region

      # celery
      CELERY_BROKER_URL: redis://:gpqylk3p6l@10.10.100.150:8001/6
      #CELERY_BROKER_URL: redis://127.0.0.1:6379/0
      CELERY_WORKER_AMOUNT: 30

      OPENAI_API_BASE_BLOCK: http://52.90.104.22:30000/v1
      OPENAI_API_BASE_STREAM: http://52.90.104.22:30000/v1
      OPENAI_API_KEY: sk-1hpKQ32AIKGnai3I464444A6316348C99b5dF54d6f1bA774
      OPENAI_ORGANIZATION_ID:
      OPENAI_CHAT_MODEL_GPT_3_5_4K: gpt-3.5-turbo-0613
      OPENAI_CHAT_MODEL_GPT_3_5_16K: gpt-3.5-turbo-16k-0613
      OPENAI_CHAT_MODEL_GPT_4: gpt-4-0613
      SUMMARY_OPENAI_CHAT_MODEL: gpt-3.5-turbo-16k

      # 文本拆分
      EMBEDDING_TEXT_SPLIT_CHUNK_SIZE: 500
      EMBEDDING_TEXT_SPLIT_CHUNK_OVERLAP_SIZE: 20
      EMBEDDING_PDF_TEXT_SPLIT_CHUNK_SIZE: 2048
      EMBEDDING_PDF_TEXT_SPLIT_CHUNK_OVERLAP_SIZE: 50

      SUMMARY_TEXT_SPLIT_CHUNK_SIZE: 14336
      SUMMARY_TEXT_SPLIT_CHUNK_OVERLAP_SIZE: 50

      DETAILED_SUMMARY_TEXT_SPLIT_CHUNK_SIZE: 10240
      DETAILED_SUMMARY_TEXT_SPLIT_CHUNK_OVERLAP_SIZE: 50

      # token限制
      SUMMARY_MAX_TOKEN: 1024
      DETAILED_SUMMARY_MAX_TOKEN: 3072
      SUGGESTED_QUESTIONS_MAX_TOKEN: 1024
      QUESTION_ANSWER_MAX_TOKEN: 2048
      DOCUMENT_CONTENT_TOKEN_LIMIT: 204800
      SUMMARY_DOCUMENT_CONTENT_TOKEN_LIMIT: 102400

      # 问题最大长度
      QUESTION_MAX_LEN: 300

      # 相似度匹配阈值
      MAX_SIMILARITY_SEARCH_SCORE: 0.235
      MAX_SIMILARITY_SEARCH_COUNT: 3

      # 摘要和问题生成温度
      GENERATE_TEMPERATURE: 0.4

      # 联网搜索
      BING_SEARCH_URL: https://api.bing.microsoft.com/v7.0/search
      BING_SUBSCRIPTION_KEY: 85e161ea47d645dea4462793fcc43bf4
      WEB_SEARCH_NUM_RESULTS: 5

    volumes:
      - ./log/worker:/app/log
    networks:
      - xming
    deploy:
      mode: replicated
      replicas: 1

networks:
  xming:
    name: samepage
    external: true
